from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class Dimension(StrEnum):
    FLUENCY               = "fluency"
    CLARITY               = "clarity"
    EXPRESSION            = "expression"
    SPEECH_SIGNAL_CLARITY = "speech_signal_clarity"
    CONCISENESS           = "conciseness"


class InsightType(StrEnum):
    OVERUSES_FILLER   = "overuses_filler"
    TALKS_TOO_FAST    = "talks_too_fast"
    TOPIC_DRIFT       = "topic_drift"
    STRONG_VOCABULARY = "strong_vocabulary"
    VERBOSE_PHRASES   = "verbose_phrases"
    REPEATED_IDEAS    = "repeated_ideas"
    LOW_SIGNAL_CLARITY = "low_signal_clarity"


# ---------------------------------------------------------------------------
# Stage 1 — Recording
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class RecordingResult:
    """Output of Stage 1. Contract guarantee: 16 kHz, 16-bit, mono WAV."""
    wav_path: str
    duration_seconds: float
    created_at: datetime
    sample_rate: int = 16_000


# ---------------------------------------------------------------------------
# Stage 2 — Transcription
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Segment:
    """One Whisper segment with timing and confidence.
    Confidence is clamped to [0, 1] on construction — callers never re-normalise."""
    start: float
    end: float
    text: str
    confidence: float   # derived: 1 + avg_logprob / 5, clamped here

    def __post_init__(self) -> None:
        object.__setattr__(self, "confidence", max(0.0, min(1.0, self.confidence)))


@dataclass(frozen=True)
class Word:
    """Word-level timestamp from Whisper (v1.5)."""
    word:        str
    start:       float
    end:         float
    probability: float   # [0, 1]

    def __post_init__(self) -> None:
        object.__setattr__(self, "probability", max(0.0, min(1.0, self.probability)))


@dataclass(frozen=True)
class TranscriptionResult:
    """Stage 2 output. Errors are preserved — no autocorrection."""
    text: str
    segments: tuple[Segment, ...]
    word_count: int
    speaking_rate_wpm: float
    words: tuple["Word", ...] = ()   # v1.5 — empty on v1 sessions


# ---------------------------------------------------------------------------
# Stage 3 — Analytics
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Insight:
    """A discrete queryable pattern detected by one analytics module.
    Becomes a row in session_insights."""
    insight_type: InsightType
    value: str


@dataclass(frozen=True)
class DimensionResult:
    """Output of one analytics module."""
    dimension: Dimension
    score: float                            # 0–100
    metrics: dict                           # raw metrics → serialised to JSON in memory.py
    feedback: str                           # deterministic human-readable string
    insights: tuple[Insight, ...]
    filler_events: dict[str, int] = field(default_factory=dict)  # fluency only


@dataclass(frozen=True)
class AnalyticsBundle:
    """Stage 3 output: all five DimensionResults + weighted overall score."""
    dimensions: tuple[DimensionResult, ...]
    overall_score: float


# ---------------------------------------------------------------------------
# Memory Engine — context assembled for Stage 4
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class MemoryContext:
    """Assembled by MemoryEngine, consumed only by Stage 4 (coaching)."""
    recent_sessions: tuple[dict, ...]      # last 5: date, word_count, wpm, per-dim scores
    recurring_patterns: tuple[str, ...]    # top 3 insight types with frequency, pre-rendered
    trends: dict[str, str]                 # dimension → improving | stable | declining
    rendered: str                          # final prompt block passed to LLM


# ---------------------------------------------------------------------------
# Stage 4 — Coaching
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class CoachingResult:
    """Stage 4 output. Parsed and validated from LLM JSON response."""
    overall_assessment: str
    strengths: tuple[str, ...]
    improvements: tuple[str, ...]
    key_insight: str
    next_focus: str
    raw_json: str                          # stored for audit / debug


# ---------------------------------------------------------------------------
# Communication Profile — persistent cross-session summary
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class CommunicationProfile:
    """Generated by MemoryEngine from all accumulated sessions. Not per-session."""
    strengths: tuple[str, ...]
    recurring_weaknesses: tuple[str, ...]
    trends: dict[str, str]
    persistent_fillers: tuple[dict, ...]
    notable_pattern: str
    narrative: str = ""   # v1.5 — LLM-generated paragraphs


# ---------------------------------------------------------------------------
# Stage 5 — Final pipeline output
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SessionResult:
    """Complete output of one pipeline run. Passed to the UI for rendering."""
    session_id: int
    recording: RecordingResult
    transcription: TranscriptionResult
    analytics: AnalyticsBundle
    coaching: CoachingResult
    profile: CommunicationProfile